# Site settings
title: Lamyaa sadiq
email: lamyaasadiq@aol.com
url: lamiae-sadiq.github.io
description2: "Digital Technologies Architecture Student "
repository: lamiae-sadiq/lamiae-sadiq.github.io

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#091109'
  links: '#d8ecd7'

# Footer settings
footer: Your Website

# "UA-NNNNNNNN-N"
google_analytics: G-L68E9YQ3WE

# resume pdf public link in google drive
google-drive-resume-file-id: 16aj6nKw01l6u5hj2c51gV0dtQSCcZTPo

# Social networks usernames
social:
  - title: github
    url: https://github.com/lamiae-sadiq
  - title: linkedin
    url: https://www.linkedin.com/in/lamyaa-sadiq-b10a79209/

projects:
  - title: "Ft_transcendence"
    venue-publication: ft_transcendence is an onepage website provide a real-time multiplayer online Pong game, chat (private/groupe messages), friend list, profiles, 42API-Auth/google 2fa, match-making system, and a spectating system
    url: https://github.com/lamiae-sadiq/ft_transcendence
  - title: "Webserv"
    venue-publication: This project is about writing an HTTP server in C++ 98 capable of processing HTTP requests.
    url: https://github.com/lamiae-sadiq/WebServer
  - title: "Minishell"
    venue-publication: This project involves creating a simple shell, akin to a mini bash. The aim is to gain a deeper understanding of processes and file descriptors.
    url: https://github.com/lamiae-sadiq/minishell
  - title: "Inception"
    venue-publication: The goal of this project is to set up a small infrastructure with Docker, following specific rules, which consists of three services (MariaDB, WordPress, and Nginx).

# Build settings
markdown: kramdown
permalink: pretty
